# Pandas Foundations

## 첫 번째 질문

데이터가 6행이라면 눈으로 직접 확인할 수 있습니다. 그런데 데이터가 10만 행이라면 어떻게 해야 할까요?

| name | score | city |
|---|---:|---|
| 민수 | 78 | 서울 |
| 지수 | 95 | 부산 |
| 영희 | 84 | 서울 |
| 철수 | 65 | 대전 |
| 유진 | 91 | 서울 |
| 현우 | 88 | 부산 |

6명 중 가장 높은 점수는 눈으로 찾을 수 있습니다. 그럼 100,000명이라면 어떨까요?

## 오늘 하게 될 일

데이터를 **살펴보고 → 선택하고 → 조건으로 찾고 → 계산하고 → 정렬합니다.**

목표는 함수 이름을 많이 외우는 것이 아니라, 질문에 맞는 데이터를 직접 찾는 것입니다.

### 마지막에는 이런 데이터도 다룹니다

`sale_id`, `buyer_id`, `sold_at`, `item_group`, `unit_price`, `units`, `coupon_rate`, `store`

지금은 낯설어도 괜찮습니다. 강의 마지막에는 처음 보는 데이터를 스스로 살펴봅니다.

## 1. Pandas 불러오기

Pandas를 사용하려면 먼저 Python에게 이 도구를 사용하겠다고 알려줍니다.

In [4]:
! pip install --upgrade pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 3.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed pandas-3.0.5

In [1]:
import pandas as pd

/opt/anaconda3/lib/python3.13/site-packages/pandas/core/computation/expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
pd.__version__

'3.0.5'

## 2. 첫 번째 데이터

작은 데이터부터 시작하면 코드의 결과를 눈으로 직접 검증할 수 있습니다.

In [ ]:
students = pd.DataFrame({
    "name": ["민수", "지수", "영희", "철수", "유진", "현우"], # "name" column 하위 6개 row에 "민수", "지수", "영희", "철수", "유진", "현우" 값을 넣음.
    "score": [78, 95, 84, 65, 91, 88], # "score" column 하위 6개 row에 값들을 넣음...
    "city": ["서울", "부산", "서울", "대전", "서울", "부산"],
    "study_hours": [3, 7, 5, 2, 6, 5],
})

In [77]:
students["name"]

0    민수
1    지수
2    영희
3    철수
4    유진
5    현우
Name: name, dtype: str

### 실행하기 전에

이 데이터는 몇 행 몇 열일까요?

- 행: ___
- 열: ___

In [ ]:
students

(6, 4)

## DataFrame

Pandas에서 **행과 열을 가진 2차원 표 형태 데이터**를 DataFrame이라고 부릅니다.

- 행(row)
- 열(column)
- 값(value)

### 데이터가 얼마나 큰가요?

10만 행을 직접 세지 않고 행과 열의 개수를 확인해봅시다. 실행 전에 결과의 모양을 예상하세요.

In [ ]:
students.shape

`shape`의 결과는 `(행의 수, 열의 수)` 순서입니다.

In [6]:
students.columns

Index(['name', 'score', 'city', 'study_hours'], dtype='str')

### 짧은 연습

`students`의 크기와 열 이름을 직접 확인하세요.

In [ ]:
# 데이터의 행과 열 개수를 확인하세요.
# 데이터의 열 이름을 확인하세요.
pass

<details>
<summary>힌트 보기</summary>

크기에는 `shape`, 열 이름에는 `columns`를 사용할 수 있습니다.

</details>

### 값의 종류도 확인해봅시다

점수 `88`과 도시 `"부산"`을 Pandas는 같은 종류의 값으로 볼까요?

In [ ]:
# 각 컬럼 별 값들의 타입을 알려준다. 
students.dtypes 

# 컬럼의 타입이 'str'이라는 것이다. 
students.columns
# >>> Index(['name', 'score', 'city', 'study_hours'], dtype='str')

name             str
score          int64
city             str
study_hours    int64
dtype: object

### 처음과 끝에서 일부만 보기

큰 데이터를 전부 출력하기보다 먼저 일부 행을 확인하는 습관을 들입니다.

In [8]:
students.head()

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5
3   철수     65   대전            2
4   유진     91   서울            6

`head(3)`은 몇 행을 보여줄까요? 실행 전에 예상해보세요.

In [9]:
students.head(3)

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5

In [10]:
students.tail(2)

  name  score city  study_hours
4   유진     91   서울            6
5   현우     88   부산            5

In [11]:
# students 데이터의 마지막 3행을 확인하세요.
students.tail(3)

  name  score city  study_hours
3   철수     65   대전            2
4   유진     91   서울            6
5   현우     88   부산            5

<details>
<summary>힌트 보기</summary>

마지막 행들을 확인할 때는 `tail()`을 사용합니다.

</details>

## 3. 필요한 열만 선택하기

전체 표가 아니라 **점수만** 보고 싶다면 어떻게 해야 할까요?

In [18]:
students["score"]

0    78
1    95
2    84
3    65
4    91
5    88
Name: score, dtype: int64

### Series

DataFrame에서 한 열을 선택하면 보통 1차원 데이터인 Series가 됩니다.

- 전체 표 → DataFrame
- 한 열 → 보통 Series

In [12]:
type(students), type(students["score"])

(pandas.DataFrame, pandas.Series)

이름과 점수 두 열을 함께 선택하면 결과는 Series일까요, DataFrame일까요?

In [ ]:
students[["name", "score"]]

  name  score
0   민수     78
1   지수     95
2   영희     84
3   철수     65
4   유진     91
5   현우     88

In [14]:
type(students[["name", "score"]])

pandas.DataFrame

안쪽의 `["name", "score"]`는 선택할 열 이름의 목록이고, 바깥 대괄호는 DataFrame에서 그 열들을 고릅니다.

In [ ]:
# city 열만 선택하세요.
# name과 city 열을 함께 선택하세요.
pass

In [ ]:
# 한 열 선택 결과와 두 열 선택 결과의 type을 각각 확인하세요.
pass

## 4. 행과 열을 함께 선택하기

`loc`은 **라벨**, `iloc`은 **위치**를 기준으로 찾습니다.

### loc: Location
- 이름 기준: 로우 이름이나 컬럼 이름(라벨)을 직접 적어서 데이터를 찾는다. 
    - '이름(name)' 또는 '라벨(label)'이란, '인덱스(index)'와 '컬럼(column)'을 통틀어 부르는 말이다.
        - 인덱스: 표의 행(row)를 식별하는 눈금이다. 0행은 Index 0, 1행은 index 1, 2행을 index 2 ....
        - 컬럼: 표의 열(column)을 식별하는 눈금이다.
        - 라벨 | 이름: 인덱스와 컬럼 자리에 실제로 적혀있는 문자나 숫자 **값**. pandas에서는 **라벨**과 **이름**을 같은 의미로 쓴다. 
            - 행 라벨(Row label): 인덱스 자리에 적힌 값들이다. students 데이터프레임에서는 0, 1, 2, 3, 4, 5
            - 열 라벨(Column label): 컬럼 자리에 적힌 값들이다. students 데이터프레임에서는 "name", "score", "city", "study_hours"
    - ex) loc[1]: 1번 행을 리턴한다.
    - ex)
- 범위 특징: 시작점부터 끝점까지 이름 그대로 모두 포함한다. 
    - ex) loc[0:2]: 0, 1, 2번 행을 모두 리턴한다.

In [21]:
students

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5
3   철수     65   대전            2
4   유진     91   서울            6
5   현우     88   부산            5

In [ ]:
students.loc[0]
students.loc[1] # 각 컬럼의 1번 인덱스를 리턴한다.

name           지수
score          95
city           부산
study_hours     7
Name: 1, dtype: object

In [ ]:
type(students.loc[1]) # 타입은 Series다.

pandas.Series

In [30]:
students.loc[0:3]

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5
3   철수     65   대전            2

In [ ]:
# # 행 인덱스(라벨)를 '민수', '지수', '영희'로 바꾸었다고 가정해봅시다.
students_new = students.set_index("name")

# 이제 loc을 쓸 때 문자로 된 '이름(라벨)'을 넣어야 합니다.
# 아래 코드는 "민수" 행부터 "영희" 행까지 "score", "city" 컬럼에 있는 값들을 DataFrame으로 리턴하라는 의미이다.
students_new.loc["민수":"영희", ["score", "city"]]

# 행 인덱스에 붙어있는 '라벨'('이름')이 사람 이름이 되었다.

      score city
name
민수       78   서울
지수       95   부산
영희       84   서울

In [ ]:
# 행을 필터링 할 수도 있다. 
# 80점 이상인 학생들만 모든 컬럼에 대해서 받아보고 싶다면? -> DataFrame(여러 컬럼 보니깐)
students.loc[students["score"] >= 80]

# 80점 이상인 학생들만 "name" 컬럼에 대해서 받아보고 싶다면? -> Series(컬럼 하나밖에 안 보니깐)
students.loc[students["score"] >= 80, "name"]

1    지수
2    영희
4    유진
5    현우
Name: name, dtype: str

### iloc: Integer Location

- 0부터 시작하는 몇 번째 순서인 지 숫자로만 데이터를 찾는다.  
- `students.iloc[0]`은 0부터 시작해서 0 번째 순서인 행을 반환한다. 이 때 타입은 `Series`.
- `students.iloc[0:3]`은 0부터 시작해서 3개의 행을 반환한다. 즉 0,1,2번째 행을 반환한다. 이 때 타입은 `DataFrame`.

In [ ]:
students.iloc[0] # 0부터 시작해서 0번째 행을 반환한다.  

students.iloc[1] # 0부터 시작해서 1번째 행을 반환한다.

name           지수
score          95
city           부산
study_hours     7
Name: 1, dtype: object

In [ ]:
students.iloc[0:3] # 마지막 인덱스는 포함되지 않는다.

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5

In [28]:
type(students.iloc[1]) # 하나의 행만 리턴하면 Series다.

pandas.Series

In [29]:
type(students.iloc[0:3]) # 여러 개의 행을 리턴하면 DataFrame이다.

pandas.DataFrame

In [35]:
# 컬럼을 지정할 수도 있다. 단, 인덱스로 지정해야 한다. loc(<행라벨 이름(들)>, <컬럼 라벨(들)>)에서는 '컬럼 라벨'로 보고싶은 컬럼을 지정할 수 있었던 것과 다르다.

students.iloc[0:2, 0:3]

  name  score city
0   민수     78   서울
1   지수     95   부산

`loc[0:2]`는 끝 라벨 2를 포함합니다. 몇 행과 몇 열이 나올지 예상해보세요.

In [24]:
# 0부터 2개의 행, 즉 0행,1행을 리턴하는데, "name", "score" 컬럼만 반환하라.

students.loc[0:2, ["name", "score"]]

  name  score
0   민수     78
1   지수     95
2   영희     84

`iloc`의 위치 범위에서는 끝 위치가 포함되지 않습니다.

In [ ]:
students.iloc[0:3, 0:2]

In [39]:
# 첫 번째 학생의 정보를 loc으로 확인하세요.
# 처음 3명의 name과 score를 loc으로 선택하세요.
# iloc으로 첫 2행, 첫 2열을 선택하세요.

students.loc[0]

students.loc[0:2, ["name", "score"]]

students.iloc[0:2, 0:2]

  name  score
0   민수     78
1   지수     95

<details>
<summary>힌트 보기</summary>

이름이나 라벨 기준이면 `loc`, 몇 번째인지 위치 기준이면 `iloc`을 떠올리세요.

</details>

# 5. 조건에 맞는 데이터 찾기

80점 이상인 학생을 바로 고르기 전에, 각 학생이 조건에 맞는지 먼저 확인합니다.

실행하면 숫자, 이름, True/False 중 무엇이 나올까요?

In [40]:
students["score"] >= 80

0    False
1     True
2     True
3    False
4     True
5     True
Name: score, dtype: bool

### Boolean Mask

조건을 적용하면 각 행에 대해 `True / False`가 만들어집니다.

`조건 → 각 행 비교 → True / False`

In [41]:
mask = students["score"] >= 80
mask

0    False
1     True
2     True
3    False
4     True
5     True
Name: score, dtype: bool

이제 `True`인 행만 골라낼 수 있을까요?

In [43]:
students

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5
3   철수     65   대전            2
4   유진     91   서울            6
5   현우     88   부산            5

In [ ]:
students[mask]

  name  score city  study_hours
1   지수     95   부산            7
2   영희     84   서울            5
4   유진     91   서울            6
5   현우     88   부산            5

In [44]:
students[students["score"] >= 80]

  name  score city  study_hours
1   지수     95   부산            7
2   영희     84   서울            5
4   유진     91   서울            6
5   현우     88   부산            5

숫자 비교와 문자열 비교도 `조건 → True/False → 선택`이라는 흐름은 같습니다.

In [45]:
students["city"] == "서울"

0     True
1    False
2     True
3    False
4     True
5    False
Name: city, dtype: bool

In [46]:
students[students["city"] == "서울"]

  name  score city  study_hours
0   민수     78   서울            3
2   영희     84   서울            5
4   유진     91   서울            6

서울 학생이면서 점수가 80점 이상인 학생을 찾으려면 어떤 두 조건이 필요할까요?

In [47]:
students[
    (students["city"] == "서울")
    & (students["score"] >= 80)
]

  name  score city  study_hours
2   영희     84   서울            5
4   유진     91   서울            6

`&`는 그리고, `|`는 또는입니다. 여러 조건은 각각 괄호로 묶습니다.

In [ ]:
students[
    (students["city"] == "서울")
    | (students["city"] == "부산")
]

### Filtering 연습

한 문제씩 조건을 만들고, 그 조건이 `True`인 행을 선택하세요.

In [48]:
# 점수가 85점 이상인 학생을 찾으세요.
mask = students["score"] >= 85

students[mask]

  name  score city  study_hours
1   지수     95   부산            7
4   유진     91   서울            6
5   현우     88   부산            5

In [49]:
# 부산 학생만 찾으세요.
mask = students["city"] == "부산"

students[mask]

  name  score city  study_hours
1   지수     95   부산            7
5   현우     88   부산            5

In [50]:
# 부산 학생이면서 점수가 85점 이상인 학생을 찾으세요.
mask = (students["city"] == "부산") & (students["score"] >= 85)

students[mask]

  name  score city  study_hours
1   지수     95   부산            7
5   현우     88   부산            5

In [51]:
# 서울 또는 부산에 사는 학생을 찾으세요.
mask = (students["city"] == "부산") | (students["city"] == "서울")

students[mask]

  name  score city  study_hours
0   민수     78   서울            3
1   지수     95   부산            7
2   영희     84   서울            5
4   유진     91   서울            6
5   현우     88   부산            5

<details>
<summary>힌트 보기</summary>

조건 하나를 먼저 True/False로 만든 뒤 DataFrame의 대괄호 안에 넣어보세요. 두 조건은 각각 괄호로 묶습니다.

</details>

### 내가 이해한 Boolean Filtering

조건을 만들면 각 행마다 __________가 만들어지고, 그 결과를 이용해 __________인 행만 선택할 수 있습니다.

# 6. 계산하기

점수를 하나씩 더하지 않고 평균을 바로 구할 수 있을까요? 실행 전에 대략 어느 정도일지 예상하세요.

In [74]:
students["score"].mean()

np.float64(83.5)

In [53]:
students["score"].max()

95

In [54]:
students["score"].min()

65

In [55]:
students["score"].sum()

np.int64(501)

In [ ]:
# study_hours의 평균을 구하세요.
# 가장 긴 공부 시간을 구하세요.
# 전체 공부 시간의 합을 구하세요.
pass

## 기존 데이터로 새로운 정보 만들기

80점 이상이면 `True`인 `passed` 열을 만듭니다. 실행 뒤 열이 몇 개가 되는지 확인하세요.

In [ ]:
# 우변의 결과, "score" 컬럼의 값이 80 이상인 지 아닌 지 T/F 값을 담은 Sereis가 반환된다. 그걸 students에 "passed" 컬럼으로 붙인다.
students["passed"] = students["score"] >= 80 
students

  name  score city  study_hours  passed
0   민수     78   서울            3   False
1   지수     95   부산            7    True
2   영희     84   서울            5    True
3   철수     65   대전            2   False
4   유진     91   서울            6    True
5   현우     88   부산            5    True

# 7. 작은 판매 데이터

가격과 수량은 있지만 주문금액은 없습니다. 기존 열로 새 값을 만들어봅니다.

In [60]:
sales = pd.DataFrame({
    "product": ["키보드", "마우스", "노트"],
    "price": [50000, 25000, 3000],
    "quantity": [1, 2, 3],
})
sales

  product  price  quantity
0     키보드  50000         1
1     마우스  25000         2
2      노트   3000         3

각 상품의 `가격 × 수량`을 손으로 먼저 계산한 뒤 아래 셀의 결과를 예상하세요.

In [ ]:
# Series와 Series를 곱하면, 그 곱한 값이 들어있는 Series가 리턴된다.
sales["price"] * sales["quantity"]

0    50000
1    50000
2     9000
dtype: int64

In [62]:
sales["sales"] = sales["price"] * sales["quantity"]
sales

  product  price  quantity  sales
0     키보드  50000         1  50000
1     마우스  25000         2  50000
2      노트   3000         3   9000

In [63]:
sales["discount"] = [0.1, 0.0, 0.2]
sales

  product  price  quantity  sales  discount
0     키보드  50000         1  50000       0.1
1     마우스  25000         2  50000       0.0
2      노트   3000         3   9000       0.2

In [65]:
# 할인 전 sales와 discount를 이용해 discount_amount 열을 만들어보세요.
sales["discount_amount"] = sales["sales"] * sales["discount"]
sales

  product  price  quantity  sales  discount  discount_amount
0     키보드  50000         1  50000       0.1           5000.0
1     마우스  25000         2  50000       0.0              0.0
2      노트   3000         3   9000       0.2           1800.0

# 8. 순서 바꾸기

가장 높은 점수부터 보고 싶다면 정렬 방향도 지정해야 합니다.

In [ ]:
# 정렬의 기본값은 오름차순이다.
students.sort_values("score")

  name  score city  study_hours  passed
3   철수     65   대전            2   False
0   민수     78   서울            3   False
2   영희     84   서울            5    True
5   현우     88   부산            5    True
4   유진     91   서울            6    True
1   지수     95   부산            7    True

In [ ]:
# 정렬 시 원본은 손상되지 않는다. 
students

  name  score city  study_hours  passed
0   민수     78   서울            3   False
1   지수     95   부산            7    True
2   영희     84   서울            5    True
3   철수     65   대전            2   False
4   유진     91   서울            6    True
5   현우     88   부산            5    True

In [ ]:
students.sort_values("score", ascending=False) # 내림차순

  name  score city  study_hours  passed
1   지수     95   부산            7    True
4   유진     91   서울            6    True
5   현우     88   부산            5    True
2   영희     84   서울            5    True
0   민수     78   서울            3   False
3   철수     65   대전            2   False

In [ ]:
# study_hours가 긴 학생부터 정렬하세요.
# 정렬 시 같은 값을 갖고있는 행들은 원래 순서 그대로 정렬된다. 
students.sort_values("study_hours", ascending=False)

  name  score city  study_hours  passed
1   지수     95   부산            7    True
4   유진     91   서울            6    True
2   영희     84   서울            5    True
5   현우     88   부산            5    True
0   민수     78   서울            3   False
3   철수     65   대전            2   False

# 9. 값의 개수 세기

서울, 부산, 대전 학생은 각각 몇 명일지 먼저 손으로 예상하세요.

In [72]:
students["city"].value_counts()

city
서울    3
부산    2
대전    1
Name: count, dtype: int64

In [73]:
# passed 값이 True인 학생과 False인 학생은 각각 몇 명인지 확인하세요.
students["passed"].value_counts()

passed
True     4
False    2
Name: count, dtype: int64

# Foundations 정리

| 질문 | 사용한 방법 |
|---|---|
| 데이터가 얼마나 크지? | `shape` |
| 어떤 열이 있지? | `columns` |
| 어떤 종류의 값이지? | `dtypes` |
| 처음 몇 행은? | `head()` |
| 필요한 열은? | `[]` |
| 특정 행과 열은? | `loc`, `iloc` |
| 조건에 맞는 데이터는? | Boolean Filtering |
| 평균과 합계는? | `mean`, `sum` |
| 새 정보를 만들 수 있나? | 새 열 생성 |
| 높은 순서로 보면? | `sort_values` |
| 값별 개수는? | `value_counts` |

## 가장 중요한 흐름

`DataFrame → 살펴보기 → 선택 → 조건 만들기 → True인 행 선택 → 계산 → 새 정보 만들기`

다음에는 처음 보는 작은 CSV에서 같은 기술을 스스로 꺼내 사용합니다.